### ISSUE TITLE
[skipjack] no bluetooth in 10-Jun-2022 nightly

### ISSUE THREAD

**Issue by megamaced** [AsteroidOS/asteroid#216]
**Describe the bug**
Fresh install of latest nightly 10-Jun-2022, bluetooth will not turn on for skipjack

**To reproduce**
1. Turn on bluetooth
2. bluetooth remains off

**Expected behavior**
Bluetooth turns on

**Comment by MagneFire** [comment]
Thanks for reporting this bug!
This issue has been reported as part of this issue too: https://github.com/AsteroidOS/asteroid/issues/212

And in our Matrix chat we found a solution for the Ticwatch S2 (`tunny`): https://matrix.to/#/!IhWLkfcitdpMucYIJB:matrix.org/$wDZDbmrZ2ef7frcz2qKhuSD9ChaNM29Ngfy0FownTbk

It consists of downgrading `bluebinder` because `/dev/rfkill` doesn't exist. Can you download and extract the attached zip file and install that on your watch? Reboot it and Bluetooth should work.
Instructions on how to install a package via SSH are listed here: https://asteroidos.org/wiki/package-installation/#packageinstallation

[bluebinder.zip](https://github.com/AsteroidOS/asteroid/files/8984466/bluebinder.zip)

**Comment by megamaced** [comment]
@MagneFire yes can confirm installing that bluebinder resolves the issue  for me

**Comment by megamaced** [comment]
just realised the vibration doesn't seem to work either
