### ISSUE TITLE
Bitbake fails in python2.7 virtualenv

### ISSUE THREAD

**Issue by tulsileathers** [AsteroidOS/asteroid#75]
Attempting to build on Arch Linux where my default python 3.7. I have no reason to change my default system python. Instead I would like to use a virtualenv.  I've ran . ./prepare-build.sh dory from within a python2.7 virtualenv. It completes successfully. I then run the bitbake command with the following output

> 2159 ± bitbake asteroid-image                   
ERROR: Unable to start bitbake server
ERROR: Server log for this session (/home/tulsi/projects/asteroid/build/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 30311 at 2018-08-16 11:20:07.595971 ---
ERROR: Layer directory '\' does not exist! Please check BBLAYERS in /home/tulsi/projects/asteroid/build/conf/bblayers.conf

Any thoughts?

**Comment by FlorentRevest** [comment]
The problem is not related to your python version but to the content of _/home/tulsi/projects/asteroid/build/conf/bblayers.conf_
What shell did you use to source prepare-build.sh ? It has been reported that some recent versions of zsh don't output the file correctly. https://github.com/AsteroidOS/asteroid/blob/master/prepare-build.sh#L117
I had a fix for that but life got in the way and I still need to find some time to get what I wanted done.
